# Project specific config

#http://lint.travis-ci.org/

language:
    - python

python:
    - "3.5"

env:
  - ATOM_CHANNEL=stable
  - ATOM_CHANNEL=beta

os:
    - linux

install:
  - python3 -m pip install requests

script: './BUILDME'

notifications:
  email:
    on_success: never
    on_failure: change

git:
  depth: 10

sudo: false

addons:
    apt:
        packages:
        - build-essential
        - git
        - libgnome-keyring-dev
        - fakeroot

branches:
  only:
    - master
